proxy:
  name: wpproxy
  labels:
    app: proxy
    env: dev
    id: c0905650
  image:
    repository: shahnoor786/nginx-proxy
    tag: latest
    pullPolicy: Always
  replicas: 10
  configmap:
  ## KEY: "value"
  APP_ENV: "dev"
  containerPorts:
      http: 80
