---
# Source: wordpress-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wpproxy
  labels:
    app: proxy
    env: dev
    stack: wordpress
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 80      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: proxy
    env: dev
    stack: wordpress       # Pod label that service is using to select Pods
